# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-12 06:50
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationconfig',
            name='country',
            field=django_countries.fields.CountryField(default=b'HR', max_length=2),
        ),
        migrations.AlterField(
            model_name='locationconfig',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default=b'Europe/Zagreb'),
        ),
    ]
