# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgm', '0022_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgeinterfaceconfig',
            name='accept_input_packages',
            field=models.BooleanField(default=False, verbose_name='Accept input packages'),
        ),
        migrations.AddField(
            model_name='ethernetinterfaceconfig',
            name='accept_input_packages',
            field=models.BooleanField(default=False, verbose_name='Accept input packages'),
        ),
        migrations.AddField(
            model_name='mobileinterfaceconfig',
            name='accept_input_packages',
            field=models.BooleanField(default=False, verbose_name='Accept input packages'),
        ),
        migrations.AddField(
            model_name='wifiinterfaceconfig',
            name='accept_input_packages',
            field=models.BooleanField(default=False, verbose_name='Accept input packages'),
        ),
    ]
