# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-11 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgm', '0023_auto_20181102_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiinterfaceconfig',
            name='wlan_encryption',
            field=models.CharField(choices=[(b'none', b'Open'), (b'psk2', b'WPA2-PSK')], default=b'none', max_length=5, verbose_name='WLAN encryption'),
        ),
    ]
