# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-11 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgm', '0024_wifiinterfaceconfig_wlan_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiinterfaceconfig',
            name='wlan_key',
            field=models.CharField(blank=True, help_text=b'Needed only if WLAN encryption is not Open', max_length=64, verbose_name='WLAN key'),
        ),
    ]
