# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-25 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eoip', '0002_eoiptunnelconfig_ip_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoiptunnelconfig',
            name='ip_family',
            field=models.CharField(choices=[(b'ipv4', b'IPv4'), (b'ipv6', b'IPv6')], default=b'ipv4', max_length=5, verbose_name='IP Family'),
        ),
    ]
