# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-02 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eoip', '0003_auto_20181025_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eoiptunnelconfig',
            name='ip_family',
            field=models.CharField(choices=[(b'-4', b'IPv4'), (b'-6', b'IPv6')], default=b'-4', max_length=5, verbose_name='IP Family'),
        ),
    ]
