# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-02 17:55
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import nodewatcher.core.registry.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cgm', '0023_auto_20181102_1210'),
        ('eoip', '0005_auto_20181102_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoiptunnelconfig',
            name='bridge_interface',
            field=nodewatcher.core.registry.fields.ReferenceChoiceField(blank=True, help_text='Select bridge to bind to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cgm.BridgeInterfaceConfig'),
        ),
    ]
