# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-02 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eoip', '0006_eoiptunnelconfig_bridge_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoiptunnelconfig',
            name='custom_route',
            field=models.CharField(blank=True, max_length=100, verbose_name='Custom route to be executed'),
        ),
    ]
