# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-04 21:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eoip', '0007_eoiptunnelconfig_custom_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoiptunnelconfig',
            name='mtu',
            field=models.PositiveIntegerField(default=1458, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9000)], verbose_name='MTU'),
        ),
    ]
