# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-12 06:50
from __future__ import unicode_literals

from django.db import migrations
import nodewatcher.core.registry.fields


class Migration(migrations.Migration):

    dependencies = [
        ('defaults_network_profile', '0008_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkprofileconfig',
            name='wireless_mesh_type',
            field=nodewatcher.core.registry.fields.RegistryChoiceField(b'node.config', b'network.profile#wireless_mesh_type', blank=True, choices=[(None, 'Disable wireless meshing'), (b'ad-hoc', 'Ad-hoc'), (b'80211s', '802.11s')], default=b'ad-hoc', help_text='Type of interface that should be used for wireless meshihng.', max_length=50, null=True),
        ),
    ]
