# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cgm', '0021_bridge_uplink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPDaemonConfig',
            fields=[
                ('packageconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cgm.PackageConfig')),
                ('community', models.CharField(max_length=100, verbose_name='SNMP Community')),
                ('location', models.CharField(max_length=100, verbose_name='Device location')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
            bases=('cgm.packageconfig',),
        ),
    ]
